Check for account approval during checkin
sleepy-hacks/WAMA pull request #133
Opened 2017-02-05 01:43 UTC by iamcreasy

2017-02-06 15:47 UTC, dubeme requested changes
See comments

2017-02-06 15:47 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                if(userAccount == null || loginCredential == null)
This condition is too broad, can you look into making it a bit more specific.

2017-02-06 15:47 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                if(userAccount == null || loginCredential == null)
Here's my breakdown of the possible scenarios, hopefully it's helpful with breaking this down

loginCredential = lc
userAccount = ua


**lc == null** // No login credential

* Possible solutions
  * If **ua == null** (see below for how to deal with it)
  * Else
    * Most likely, the account hasn't been verified - (Talk to the front desk folks)
    * Something catastrophic has happened - (Don't worry about this)

**ua == nul**l // No user account
* No account with the member ID exists, create new account

2017-02-11 23:09 UTC, iamcreasy commented on app/wama.web/Controllers/CheckInController.cs
> +                if(userAccount == null || loginCredential == null)
How about the following?

```
if ua == null
    Message(ID_Does_not_exits)
else {
    if( !userAccount.HasBeenApproved)
        Message(Account_Approval_Pending)
    else 
        checkin_sucessful_page
}
```

2017-02-12 01:03 UTC, dubeme requested changes

2017-02-12 01:03 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                if(userAccount == null || loginCredential == null)
Looking good

2017-02-12 01:36 UTC, closed without merging