4 Minor features
sleepy-hacks/WAMA pull request #189
Opened 2017-03-25 22:30 UTC by iamcreasy

New features in this pull request,
1. Signature at waiver aggrement page in now case insensitive
2. If the usre have a certificate and if the certification is expired, the user can not log-in
3. Both log-in and account creation page accepts 6 digit member id
4. Use can not check in if his account is suspended

2017-03-26 00:06 UTC, sakurano92 commented on app/wama.web/AppString.resx
> +    <value>Your account has been suspecded! Please contact the front desk.</value>
spelling mistake suspecded -> suspended please update

2017-03-26 00:06 UTC, AboodV2 reviewed
It looks good for me

2017-03-26 21:30 UTC, dubeme requested changes
Almost there, see comments

2017-03-26 21:30 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                    SetErrorMessages(AppString.CertificateExpired);
When a certification expires, a patron can still login.
Hence, you should figure out a means to pass a warning message to the Successful page.

2017-03-26 21:30 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                else if (certificateInfo != null && System.DateTimeOffset.Compare(System.DateTimeOffset.Now, certificateInfo.ExpiresOn) > 0)
The name certificationInfo can be simplified to certification. It's less redundant.

2017-03-26 21:30 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            string userName = userAccount.FirstName + " " + userAccount.LastName;
Don't just assume that the userAccount will always exist. 
Something weird can happen en-route to the DB, hence resulting in null being returned.

Perform proper checks for null on this variable.

2017-03-26 21:30 UTC, dubeme commented on app/wama.web/Views/CheckIn/Index.cshtml
> +                       title="6 or 7 digit long numbers only!" />
Also, update the ViewModel used to generate these forms

2017-03-27 03:01 UTC, dubeme requested changes
Still missing the ViewModels tha's used in generating the forms.

Also, still missing some null checks (or perhaps, a better default value).

2017-03-27 03:01 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            string userName = null;
Nice, but not quite. If this is null, then (SEE NEXT COMMENT)

2017-03-27 03:01 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            if (signerName == null || (userName != null && !signerName.ToLower().Equals(userName.ToLower())))
userName.Lower(), will raise a NullReferenceException

2017-03-27 04:37 UTC, iamcreasy commented on app/wama.web/Controllers/CheckInController.cs
> +            if (signerName == null || (userName != null && !signerName.ToLower().Equals(userName.ToLower())))
It won't because && is a short circuit operator.

2017-03-27 05:23 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            if (signerName == null || (userName != null && !signerName.ToLower().Equals(userName.ToLower())))
Ahh! didn't see that.

2017-03-27 05:24 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            if (signerName == null || (userName != null && !signerName.ToLower().Equals(userName.ToLower())))
Then just fix the view models, and you're good to go

2017-03-30 00:58 UTC, iamcreasy commented on app/wama.web/Views/CheckIn/Index.cshtml
> +                       title="6 or 7 digit long numbers only!" />
Updated UserAccountViewModel.cs with 4713ba3a33644fa0af881433338bd19c876a15ab

2017-04-01 22:29 UTC, iamcreasy commented on app/wama.web/Views/CheckIn/Index.cshtml
> +                       title="6 or 7 digit long numbers only!" />
Updated CheckInController.cs with a2f846bee85c740d2db37321a1f5b9318f165e6a

2017-04-01 23:46 UTC, dubeme requested changes
See comments

2017-04-01 23:46 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            if (ModelState.IsValid &&  !string.IsNullOrWhiteSpace(memberId) && (memberId.Length == 6 || memberId.Length == 7))
Nice, but not quite. I think there's a better way to achieve this with attributes

2017-04-01 23:46 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +            if (signerName == null || (userName != null && !signerName.ToLower().Equals(userName.ToLower())))
This looks good, but what about something like this.

(string.IsNullOrWhiteSpace(signerName) || string.IsNullOrWhiteSpace(userName) || !signerName.Equals(userName, StringComparison.OrdinalIgnoreCase))

2017-04-03 16:38 UTC, dubeme requested changes

2017-04-03 16:38 UTC, dubeme commented on app/wama.core/ViewModel/User/UserAccountViewModel.cs
> +        [MaxLength(7, ErrorMessage = "Member ID length should be either 6 or 7 digits long."), MinLength(6)]
To make things easier to read, move the MinLength attribute to it's own line

2017-04-03 16:38 UTC, dubeme commented on app/wama.web/Views/Patron/Create.cshtml
> -                   title="Member ID must be in number and 7 digit long."
Looks like you forgot to put this one back.

2017-04-03 16:45 UTC, iamcreasy commented on app/wama.web/Views/Patron/Create.cshtml
> -                   title="Member ID must be in number and 7 digit long."
If it put it back then the error message in the attribute does not kick in?

2017-04-03 17:17 UTC, dubeme requested changes

2017-04-03 17:17 UTC, dubeme commented on app/wama.web/Views/Patron/Create.cshtml
> -                   title="Member ID must be in number and 7 digit long."
Yep, that's true.

But you're still not seeing/understanding how these validations work.
Or, why they're needed.
Think of, and answer these questions.

* Where should the validation happen if I use a browser that doesn't support HTML5?
* Where should the validation happen if I use a browser that supports HTML5?
* Should the request always have to go back to the server in other for validation to happen?

2017-04-06 13:26 UTC, sakurano92 commented
well quazi, i thought we talked about this last saturday, you put data check method in both view (HTML) and viewmodel (enumerable) side since, 
view gives user why they shouldnt doing it
viemodel gives server and maintenance personal that why there is some strange data try to implemented into.

since html gives the feedback to User, html checking method should remain inthere

and also viewmodel checking is required (which ive seen you implemented) because to make sure not to have some garbage data (or unwanted data) into database when somebody (maintenance, administer so on) try to change something or maintain into it.

2017-04-07 04:28 UTC, dubeme approved these changes

2017-04-07 04:28 UTC, merged