Changes to AdminConsole View
sleepy-hacks/WAMA pull request #207
Opened 2017-04-02 06:46 UTC by israelCyabukombe

Changes were made to the following files:
                   -Index.cshtml
                   -AdminConsoleController.cs

2017-04-02 08:33 UTC, iamcreasy commented
If you can mention what are the changes you've made in this pull request, it will be easier for me to review it.

2017-04-02 18:59 UTC, israelCyabukombe commented
It looks like it has added/included my old pull requests. The last 2 are the changes but ill fork a new repo since I solve it in got shell

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
From: Quazi Irfan <notifications@github.com>
Sent: Sunday, April 2, 2017 3:33:29 AM
To: sleepy-hacks/WAMA
Cc: Cyabukombe, Israel - SDSU Student; Author
Subject: Re: [sleepy-hacks/WAMA] Changes to AdminConsole View (#207)


If you can mention what are the changes you've made in this pull request, it will be easier for me to review it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/sleepy-hacks/WAMA/pull/207#issuecomment-290972700>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AWJbxyoVupgSKtHRvz_iooNl30XlsLQyks5rr11ZgaJpZM4MwuBo>.

2017-04-03 17:00 UTC, iamcreasy commented
But you still didn't say what you pull request does.

2017-04-03 17:09 UTC, dubeme requested changes

2017-04-03 17:09 UTC, dubeme commented on app/wama.web/Controllers/AdminController.cs
> +                    return RedirectToAction(nameof(AdminAccessLogin));
This is good.

But, for a good User Experience. If you're going to return the user to the login page again, it would be nice to have a message explaining why.

2017-04-06 17:58 UTC, closed without merging