user account service test implemented
sleepy-hacks/WAMA pull request #210
Opened 2017-04-08 19:40 UTC by sakurano92

User account service test for few test that left out blank
has been implemented

2017-04-08 19:55 UTC, dubeme requested changes
Not bad, the main issue has to do with you using numbers for boolean. For readability, and reducing level of confusion, switch to using an actual boolean value (true or false).

2017-04-08 19:55 UTC, dubeme commented on app/wama.core.unit.test/Services/UserAccountServiceTests.cs
> +        [InlineData("8521473", 1)]
Change the numbers to an actual boolean value (**_true_** or **_false_**)

2017-04-08 20:00 UTC, sakurano92 commented on app/wama.core.unit.test/Services/UserAccountServiceTests.cs
> +        [InlineData("8521473", 1)]
oh yea forgot about it

2017-04-08 23:48 UTC, iamcreasy commented
expectedCount in GetPendingUserAccountsAsyncTest test is being testing against zero. Is this correct?

2017-04-09 00:07 UTC, dubeme approved these changes

2017-04-09 00:07 UTC, merged

2017-04-09 00:10 UTC, quazi-irfan commented on app/wama.core.unit.test/Services/UserAccountServiceTests.cs
> +        public async Task GetPendingUserAccountsAsyncTest(UserAccountType accountType, int expectedCount)
expectedCount in GetPendingUserAccountsAsyncTest test is being testing against zero. Is this correct?