artificial delay before redirect to checkin #86
sleepy-hacks/WAMA pull request #91
Opened 2017-01-20 01:49 UTC by sakurano92

simple timer added need to work on but will delay for 10 seconds for now
still need to add following:
1. separate that delay to single class so can be implemented whenever needed delay (i need help for this)
2. have to show on UI that it will redirect with in 10 seconds... (new html? or just show on same page?)

2017-01-20 05:29 UTC, dubeme requested changes
Nice start, but will need some adjustment.

Remember that the tasks asks for delaying before redirecting. Currently you're delaying before taking any action at all.

You should instead delay before the call to "RedirectToAction".

2017-01-21 19:48 UTC, dubeme commented on app/wama.web/Controllers/PatronController.cs
> +        public IActionResult Create(string ReceavedId)
"**ReceavedId**" is supposed to be "**receivedId**".

**Apart** from that, you should rename the variable to "**memberId**", this tells me when reading the code that the parameter is a Member Id.

2017-01-21 19:48 UTC, dubeme commented on app/wama.web/Controllers/PatronController.cs
> +            ViewBag.MemberId = ReceavedId;
Also here

2017-01-21 19:50 UTC, dubeme commented on app/wama.web/Controllers/CheckInController.cs
> +                        routeValues: new { ReceavedId = memberId });
See comment below about renaming the variable

2017-01-21 19:51 UTC, dubeme requested changes
Almost there, see comments on minor changes to make.

2017-01-21 23:20 UTC, sakurano92 commented on app/wama.web/Controllers/CheckInController.cs
> +                        routeValues: new { ReceavedId = memberId });
so fix the naming from ReceavedId to memberId will be all?

2017-01-22 05:04 UTC, dubeme requested changes
Nice work, Sang Won

2017-01-22 05:04 UTC, dubeme approved these changes

2017-01-22 05:05 UTC, merged